// Command wombat-tsgen emits TypeScript declarations for the event stream and
// for the HTTP API.
//
//	go run ./cmd/wombat-tsgen > web/events.ts
//
// A front end consuming the SSE or JSONL stream needs the shape of every
// event, and a front end talking to httpapi needs the shape of every request
// and response. Hand-writing either is a chore once and a bug forever: the day
// someone adds a variant or renames a field, the hand-written copy is silently
// wrong and tsc happily vouches for it.
//
// The output is a .ts and not a .d.ts: it carries one real function, isKind,
// and a declaration file may not have an implementation.
//
// So the declarations are derived from the Go types by reflection — over
// [wombat.EventTypes] for the stream and [httpapi.APITypes] for the API —
// which means they cannot describe a field that does not exist. What they
// still cannot catch is a new type left out of one of those registries, which
// is why each registry lives beside the types it names and is the only list to
// keep.
//
// wombat.Event is an open interface, so wombat.EventTypes is not the only
// event registry: a layer built on top defines its own variants and they
// travel in the same stream. That openness is worth what it costs, and this is
// the cost — every such package has to be named in [eventTypes] or its events
// reach the front end as frames tsc has never heard of. [permission.EventTypes]
// and [httpapi.EventTypes] are the two.
//
// The transcript is deliberately not generated. GET /api/sessions/{id}/messages
// returns []llm.Message in the harness's own persistence shape, which httpapi
// does not own; forking a second declaration of it here would be a second
// source of truth for a format nobody in this repo is free to change anyway.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path"
	"reflect"
	"strings"
	"time"

	wombat "github.com/automanfromm87/wombat-go"
	"github.com/automanfromm87/wombat-go/httpapi"
	"github.com/automanfromm87/wombat-go/permission"
)

// eventTypes is every registry the generated union covers, concatenated in the
// order a reader wants them: the core stream first, then each layer.
func eventTypes() []wombat.Event {
	out := wombat.EventTypes()
	out = append(out, permission.EventTypes()...)
	out = append(out, httpapi.EventTypes()...)
	return out
}

func main() {
	var b strings.Builder

	b.WriteString(`// Code generated by wombat-tsgen. DO NOT EDIT.
//
// Every frame of the wombat event stream, as a discriminated union on "type",
// and every request and response body of the HTTP API.
//
//   const es = new EventSource("/api/sessions/" + id + "/events");
//   for (const kind of KINDS) {
//     es.addEventListener(kind, (m) => render(JSON.parse(m.data) as WombatEvent));
//   }
//
//   function render(ev: WombatEvent) {
//     switch (ev.type) {
//       case "text_delta": append(ev.text); break;
//       // ...
//       default: { const _: never = ev; }   // exhaustiveness, checked by tsc
//     }
//   }

`)

	events := eventTypes()
	names := make([]string, 0, len(events))
	for _, ev := range events {
		t := reflect.TypeOf(ev)
		name := tsName(t)
		names = append(names, name)

		fmt.Fprintf(&b, "export interface %s {\n", name)
		fmt.Fprintf(&b, "  type: %q;\n", ev.Kind())
		writeFields(&b, t, "  ")
		b.WriteString("}\n\n")
	}

	fmt.Fprintf(&b, "export type WombatEvent =\n  | %s;\n\n", strings.Join(names, "\n  | "))

	b.WriteString(`/** Every "type" value the stream can carry. */
export type WombatEventKind = WombatEvent["type"];

/** Narrow an event by kind: isKind(ev, "tool_done") tells tsc which fields exist. */
export function isKind<K extends WombatEventKind>(
  ev: WombatEvent,
  kind: K,
): ev is Extract<WombatEvent, { type: K }> {
  return ev.type === kind;
}

/** Every event name the SSE endpoint uses, for addEventListener. */
export const WOMBAT_EVENT_KINDS: readonly WombatEventKind[] = [
`)
	for _, ev := range events {
		fmt.Fprintf(&b, "  %q,\n", ev.Kind())
	}
	b.WriteString("];\n")

	writeAPI(&b)

	if _, err := os.Stdout.WriteString(b.String()); err != nil {
		fmt.Fprintln(os.Stderr, "wombat-tsgen:", err)
		os.Exit(1)
	}
}

// writeAPI emits the request and response bodies of the HTTP API.
func writeAPI(b *strings.Builder) {
	b.WriteString(`
// ===== HTTP API =====
//
// The bodies of github.com/automanfromm87/wombat-go/httpapi, from its own
// registry. Errors all share one envelope, so a client can parse a failure
// before it knows which endpoint produced it:
//
//   {"error": {"kind": "no_such_session", "message": "…"}}

`)

	// The enums first, since the interfaces below refer to them.
	states := make([]string, 0, len(httpapi.States()))
	for _, s := range httpapi.States() {
		states = append(states, string(s))
	}
	fmt.Fprintf(b, "/** Where a session is in its lifecycle. */\nexport type %s =\n%s;\n\n",
		tsName(stateType), union(states))

	// A union rather than a reference from SessionOptions.permission, which is
	// a plain Go string and is honestly declared as one: the server accepts the
	// field and rejects the value, so a client that widens it gets a 500 from
	// the builder rather than a lie from tsc. This is what a form's <select>
	// should be populated from.
	fmt.Fprintf(b, "/** The values SessionOptions.permission accepts. */\n"+
		"export type WombatApiPermissionMode =\n%s;\n\n", union(httpapi.PermissionModes()))

	for _, v := range httpapi.APITypes() {
		t := reflect.TypeOf(v)
		fmt.Fprintf(b, "export interface %s {\n", tsName(t))
		writeFields(b, t, "  ")
		b.WriteString("}\n\n")
	}
}

// union renders a string-literal union in the same shape as the event union
// above, so the file reads as one document rather than two.
func union(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, v := range values {
		quoted = append(quoted, fmt.Sprintf("%q", v))
	}
	return "  | " + strings.Join(quoted, "\n  | ")
}

// tsName is the interface name for one Go type.
//
// Everything is prefixed Wombat, as it always was; a type from a layer package
// carries that package's name too. Not cosmetic — the union is flat, and
// permission.Requested and a future wombat.Requested would otherwise generate
// the same interface twice and produce a .ts that does not compile. httpapi
// makes the point concrete: it defines its own Spend, and wombat.Spend already
// owns WombatSpend.
func tsName(t reflect.Type) string {
	pkg := path.Base(t.PkgPath())
	if pkg == "" || pkg == "wombat-go" {
		return "Wombat" + t.Name()
	}
	if short, ok := shortPkg[pkg]; ok {
		return "Wombat" + short + t.Name()
	}
	return "Wombat" + strings.ToUpper(pkg[:1]) + pkg[1:] + t.Name()
}

// shortPkg renames a package for the generated identifier. "WombatHttpapiSpend"
// is what the general rule produces and nobody would type it twice.
var shortPkg = map[string]string{"httpapi": "Api"}

func writeFields(b *strings.Builder, t reflect.Type, indent string) {
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		// An embedded struct with no json tag has its fields PROMOTED onto the
		// enclosing object by encoding/json, so the declaration has to inline
		// them too. httpapi.CreateRequest is the case: {"prompt":…,"model":…}
		// is one flat object on the wire, not a nested one.
		if f.Anonymous && f.Tag.Get("json") == "" && f.Type.Kind() == reflect.Struct {
			writeFields(b, f.Type, indent)
			continue
		}
		name, optional, skip := jsonName(f)
		if skip {
			continue
		}
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(b, "%s%s%s: %s;\n", indent, name, q, tsType(f.Type, indent))
	}
}

func jsonName(f reflect.StructField) (name string, optional, skip bool) {
	tag := f.Tag.Get("json")
	if tag == "-" {
		return "", false, true
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	if name == "" {
		name = f.Name
	}
	// omitempty is why a field is optional on the wire, so it is why it is
	// optional in the declaration. Getting this wrong in the other direction
	// is the expensive one: a field typed as required that the server omits
	// makes tsc vouch for something that is undefined at runtime.
	for _, p := range parts[1:] {
		if p == "omitempty" || p == "omitzero" {
			optional = true
		}
	}
	return name, optional, false
}

// rawMessage is recognised by identity, not by kind: []byte otherwise maps to
// a base64 string in Go's JSON encoding, and json.RawMessage very much does
// not.
var rawMessage = reflect.TypeOf(json.RawMessage(nil))

// timeType marshals to an RFC 3339 string, and reflecting into it would
// otherwise produce an empty object: time.Time has no exported fields.
var timeType = reflect.TypeFor[time.Time]()

// stateType is httpapi.State, emitted as a union of its values rather than as
// a bare string — the whole reason httpapi.States exists.
var stateType = reflect.TypeFor[httpapi.State]()

// named are the types that get their own declaration, so a reference to one is
// a reference and not a second inlined copy. Built from the API registry, which
// is the definition of "has its own declaration".
var named = func() map[reflect.Type]string {
	m := map[reflect.Type]string{stateType: tsName(stateType)}
	for _, v := range httpapi.APITypes() {
		t := reflect.TypeOf(v)
		m[t] = tsName(t)
	}
	return m
}()

func tsType(t reflect.Type, indent string) string {
	if t == rawMessage {
		return "unknown"
	}
	if t == timeType {
		return "string"
	}
	if n, ok := named[t]; ok {
		return n
	}

	switch t.Kind() {
	case reflect.String:
		return "string"

	case reflect.Bool:
		return "boolean"

	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"

	case reflect.Pointer:
		// A pointer field marshals to null when nil, and Go has no way to say
		// "never nil", so the honest declaration includes it.
		return tsType(t.Elem(), indent) + " | null"

	case reflect.Slice, reflect.Array:
		// A nil slice marshals to null, not []. The server takes care to send
		// [] for the collections a client iterates, which is why this is not
		// "| null" — see httpapi's listSessions and listApprovals.
		return tsType(t.Elem(), indent) + "[]"

	case reflect.Map:
		return fmt.Sprintf("Record<%s, %s>", tsType(t.Key(), indent), tsType(t.Elem(), indent))

	case reflect.Interface:
		// The only interfaces reachable from here are wombat.Event —
		// SubagentEvent.Inner and Frame.Event — and a nested event is the whole
		// union.
		return "WombatEvent"

	case reflect.Struct:
		// Inlined rather than named, unless the type has a declaration of its
		// own above. These are small value types — llm.Usage is four numbers —
		// and naming them would put wire-format types from packages this
		// generator does not cover into the output.
		var sub strings.Builder
		sub.WriteString("{\n")
		writeFields(&sub, t, indent+"  ")
		sub.WriteString(indent + "}")
		return sub.String()

	default:
		return "unknown"
	}
}
