// Code generated by wombat-tsgen. DO NOT EDIT.
//
// Every frame of the wombat event stream, as a discriminated union on "type",
// and every request and response body of the HTTP API.
//
//   const es = new EventSource("/api/sessions/" + id + "/events");
//   for (const kind of KINDS) {
//     es.addEventListener(kind, (m) => render(JSON.parse(m.data) as WombatEvent));
//   }
//
//   function render(ev: WombatEvent) {
//     switch (ev.type) {
//       case "text_delta": append(ev.text); break;
//       // ...
//       default: { const _: never = ev; }   // exhaustiveness, checked by tsc
//     }
//   }

export interface WombatIterStart {
  type: "iter_start";
  n: number;
  max: number;
}

export interface WombatLLMStart {
  type: "llm_start";
  model?: string;
  purpose?: string;
  tools: number;
  forced_tool?: string;
}

export interface WombatReasoningDelta {
  type: "reasoning_delta";
  text: string;
}

export interface WombatToolArgsDelta {
  type: "tool_args_delta";
  index: number;
  use_id?: string;
  name?: string;
  text: string;
}

export interface WombatTextDelta {
  type: "text_delta";
  text: string;
}

export interface WombatLLMDone {
  type: "llm_done";
  model?: string;
  stop_reason?: string;
  usage: {
    input_tokens: number;
    output_tokens: number;
    cache_creation_input_tokens?: number;
    cache_read_input_tokens?: number;
  };
  ms: number;
}

export interface WombatToolStart {
  type: "tool_start";
  use_id: string;
  name: string;
  category?: string;
  input?: unknown;
}

export interface WombatToolDone {
  type: "tool_done";
  use_id: string;
  name: string;
  ok: boolean;
  output?: string;
  error?: string;
  ms: number;
}

export interface WombatSpend {
  type: "spend";
  cost_usd: number;
  calls: number;
  input_tokens: number;
  output_tokens: number;
  cache_write_tokens?: number;
  cache_read_tokens?: number;
  elapsed_sec: number;
}

export interface WombatSubagentStart {
  type: "subagent_start";
  name: string;
  task: string;
  depth: number;
}

export interface WombatSubagentEvent {
  type: "subagent_event";
  name: string;
  depth: number;
  inner: WombatEvent;
}

export interface WombatSubagentEnd {
  type: "subagent_end";
  name: string;
  ok: boolean;
  error?: string;
  ms: number;
}

export interface WombatPermissionRequested {
  type: "permission_requested";
  use_id: string;
  tool: string;
  reason?: string;
  input?: unknown;
}

export interface WombatPermissionDecided {
  type: "permission_decided";
  use_id: string;
  tool: string;
  allowed: boolean;
  reason?: string;
  source?: string;
}

export interface WombatApiTurnStarted {
  type: "turn_started";
  turn: number;
  prompt: string;
}

export interface WombatApiTurnEnded {
  type: "turn_ended";
  turn: number;
  state: WombatApiState;
  outcome?: string;
  answer?: string;
  question?: string;
  tool?: string;
  error?: string;
  error_kind?: string;
  spend: WombatApiSpend;
}

export type WombatEvent =
  | WombatIterStart
  | WombatLLMStart
  | WombatReasoningDelta
  | WombatToolArgsDelta
  | WombatTextDelta
  | WombatLLMDone
  | WombatToolStart
  | WombatToolDone
  | WombatSpend
  | WombatSubagentStart
  | WombatSubagentEvent
  | WombatSubagentEnd
  | WombatPermissionRequested
  | WombatPermissionDecided
  | WombatApiTurnStarted
  | WombatApiTurnEnded;

/** Every "type" value the stream can carry. */
export type WombatEventKind = WombatEvent["type"];

/** Narrow an event by kind: isKind(ev, "tool_done") tells tsc which fields exist. */
export function isKind<K extends WombatEventKind>(
  ev: WombatEvent,
  kind: K,
): ev is Extract<WombatEvent, { type: K }> {
  return ev.type === kind;
}

/** Every event name the SSE endpoint uses, for addEventListener. */
export const WOMBAT_EVENT_KINDS: readonly WombatEventKind[] = [
  "iter_start",
  "llm_start",
  "reasoning_delta",
  "tool_args_delta",
  "text_delta",
  "llm_done",
  "tool_start",
  "tool_done",
  "spend",
  "subagent_start",
  "subagent_event",
  "subagent_end",
  "permission_requested",
  "permission_decided",
  "turn_started",
  "turn_ended",
];

// ===== HTTP API =====
//
// The bodies of github.com/automanfromm87/wombat-go/httpapi, from its own
// registry. Errors all share one envelope, so a client can parse a failure
// before it knows which endpoint produced it:
//
//   {"error": {"kind": "no_such_session", "message": "…"}}

/** Where a session is in its lifecycle. */
export type WombatApiState =
  | "idle"
  | "running"
  | "waiting"
  | "approving"
  | "done"
  | "failed";

/** The values SessionOptions.permission accepts. */
export type WombatApiPermissionMode =
  | "off"
  | "readonly"
  | "workspace"
  | "ask";

export interface WombatApiHealth {
  status: string;
  version?: string;
  uptime_sec: number;
}

export interface WombatApiCapabilities {
  version?: string;
  default_model?: string;
  permission_modes: string[];
  approvals: boolean;
  tools: WombatApiToolInfo[];
}

export interface WombatApiToolInfo {
  name: string;
  description?: string;
  category?: string;
  read_only: boolean;
}

export interface WombatApiSessionOptions {
  model?: string;
  permission?: string;
  workspace?: string;
  max_iters?: number;
  title?: string;
}

export interface WombatApiSessionInfo {
  id: string;
  title?: string;
  state: WombatApiState;
  turns: number;
  events: number;
  created: string;
  updated: string;
  options: WombatApiSessionOptions;
  spend: WombatApiSpend;
  outcome?: string;
  answer?: string;
  error?: string;
  error_kind?: string;
}

export interface WombatApiSpend {
  cost_usd: number;
  input_tokens: number;
  output_tokens: number;
  cache_read_tokens: number;
  calls: number;
  elapsed_sec: number;
}

export interface WombatApiFrame {
  seq: number;
  turn: number;
  event: WombatEvent;
}

export interface WombatApiApproval {
  use_id: string;
  tool: string;
  reason: string;
  input?: unknown;
  since: string;
}

export interface WombatApiSessionList {
  sessions: WombatApiSessionInfo[];
}

export interface WombatApiApprovalList {
  approvals: WombatApiApproval[];
}

export interface WombatApiCreateRequest {
  prompt: string;
  model?: string;
  permission?: string;
  workspace?: string;
  max_iters?: number;
  title?: string;
}

export interface WombatApiSendRequest {
  prompt: string;
}

export interface WombatApiResolveRequest {
  allow: boolean | null;
}

export interface WombatApiErrorBody {
  error: WombatApiErrorDetail;
}

export interface WombatApiErrorDetail {
  kind: string;
  message: string;
}

